title:            Flare
description:      A description here that is sure to impress.
url:              http://flare.is
signoff:          Flare Team
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
 - name:         About
    url:          /about
 - name:         Blog
    url:          http://flareinc.github.io
    external:     true
 - name:         Email
    url:          mailto:hello@flare.is
    external:     true
 - name:         GitHub
    url:          http://github.com/flareinc
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]